<a href="https://colab.research.google.com/github/K-2315/WIDS-/blob/main/WIDS%20WEEK%203%20LAB%206%20ASSIGNMENT%20SUBMISSION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np
from sklearn.datasets import make_regression
import time

np.random.seed(42)
A, y = make_regression(n_samples=200, n_features=10, noise=0.1)

y = y.reshape(-1, 1)


def newton_ols(A, y, x0, tol=1e-6, max_iter=100):
    x = x0
    for i in range(max_iter):
        grad = A.T @ (A @ x - y)
        hessian = A.T @ A
        if np.linalg.det(hessian) == 0:
            print("Hessian is not invertible at iteration", i)
            break
        delta_x = np.linalg.inv(hessian) @ grad
        x = x - delta_x
        if np.linalg.norm(delta_x) < tol:
            print(f"Converged in {i + 1} iterations.")
            return x

    print("Did not converge within the maximum number of iterations.")
    return x


def newton_regularized_ols(A, y, x0, lam, tol=1e-6, max_iter=100):
    x = x0
    for i in range(max_iter):
        grad = A.T @ (A @ x - y) + lam * x
        hessian = A.T @ A + lam * np.eye(A.shape[1])
        if np.linalg.det(hessian) == 0:
            print("Hessian is not invertible at iteration", i)
            break
        delta_x = np.linalg.inv(hessian) @ grad
        x = x - delta_x
        if np.linalg.norm(delta_x) < tol:
            print(f"Converged in {i + 1} iterations.")
            return x

    print("Did not converge within the maximum number of iterations.")
    return x
t0=time.process_time()
x0 = np.zeros((A.shape[1], 1))

print("Solving basic OLSLR problem:")
x_ols = newton_ols(A, y, x0)
print("Minimizer values = ",x_ols)
print("Value of Square of Euclidean Norm of (Ax* - y) for basic OLSLR ",np.linalg.norm(A @ x_ols - y) ** 2)

print("\nSolving regularized OLSLR problem:")
lambda_reg = 0.001
x_reg_ols = newton_regularized_ols(A, y, x0, lambda_reg)
print("Minimizer values = ",x_reg_ols)
print("Value of Square of Euclidean Norm of (Ax* - y) for regularised OLSLR ",np.linalg.norm(A @ x_reg_ols - y) ** 2)
t1=time.process_time()
print("Time taken = ",t1-t0)



Solving basic OLSLR problem:
Converged in 2 iterations.
Minimizer values =  [[29.95996856]
 [34.88593338]
 [ 7.23429824]
 [94.76512444]
 [11.09213557]
 [95.50624453]
 [40.70708442]
 [80.82025945]
 [52.26164555]
 [ 6.60582702]]
Value of Square of Euclidean Norm of (Ax* - y) for basic OLSLR  1.882944611344992

Solving regularized OLSLR problem:
Converged in 2 iterations.
Minimizer values =  [[29.9598925 ]
 [34.88573686]
 [ 7.23427589]
 [94.7646815 ]
 [11.09202598]
 [95.50569292]
 [40.70678875]
 [80.81984761]
 [52.26141276]
 [ 6.6057882 ]]
Value of Square of Euclidean Norm of (Ax* - y) for regularised OLSLR  1.8831075222043496
Time taken =  0.019102087000000267


In [9]:
import numpy as np
from sklearn.datasets import make_regression
from scipy.optimize import minimize


np.random.seed(42)
A, y = make_regression(n_samples=200, n_features=10, noise=0.1)
y = y.reshape(-1, 1)

def bfgs_ols(A, y, x0):
    def objective(x):
        x = x.reshape(-1, 1)
        return 0.5 * np.linalg.norm(A @ x - y) ** 2

    def gradient(x):
        x = x.reshape(-1, 1)
        return (A.T @ (A @ x - y)).flatten()

    result = minimize(objective, x0.flatten(), jac=gradient, method='BFGS')
    if result.success:
        print("Converged in", result.nit, "iterations.")
    else:
        print("Optimization did not converge.")
    return result.x.reshape(-1, 1)

def bfgs_regularized_ols(A, y, x0, lam):
    def objective(x):
        x = x.reshape(-1, 1)
        return 0.5 * np.linalg.norm(A @ x - y) ** 2 + 0.5 * lam * np.linalg.norm(x) ** 2

    def gradient(x):
        x = x.reshape(-1, 1)
        return (A.T @ (A @ x - y) + lam * x).flatten()

    result = minimize(objective, x0.flatten(), jac=gradient, method='BFGS')
    if result.success:
        print("Converged in", result.nit, "iterations.")
    else:
        print("Optimization did not converge.")
    return result.x.reshape(-1, 1)

t0=time.process_time()
x0 = np.zeros((A.shape[1], 1))

print("Solving basic OLSLR problem with BFGS:")
x_ols_bfgs = bfgs_ols(A, y, x0)
print("Minimizer values = ",x_ols_bfgs)
print("Value of Square of Euclidean Norm of (Ax* - y) for basic OLSLR ",np.linalg.norm(A @ x_ols_bfgs - y) ** 2)
print("\nSolving regularized OLSLR problem with BFGS:")
lambda_reg = 0.001
x_reg_ols_bfgs = bfgs_regularized_ols(A, y, x0, lambda_reg)
print("Minimizer values = ",x_reg_ols_bfgs)
print("Value of Square of Euclidean Norm of (Ax* - y) for regularised OLSLR ",np.linalg.norm(A @ x_reg_ols_bfgs - y) ** 2)
t1=time.process_time()
print("Time taken = ",t1-t0)

Solving basic OLSLR problem with BFGS:
Converged in 16 iterations.
Minimizer values =  [[29.95996856]
 [34.88593338]
 [ 7.23429824]
 [94.76512444]
 [11.09213557]
 [95.50624452]
 [40.70708442]
 [80.82025945]
 [52.26164555]
 [ 6.60582702]]
Value of Square of Euclidean Norm of (Ax* - y) for basic OLSLR  1.8829446113450894

Solving regularized OLSLR problem with BFGS:
Converged in 16 iterations.
Minimizer values =  [[29.9598925 ]
 [34.88573686]
 [ 7.23427589]
 [94.7646815 ]
 [11.09202598]
 [95.50569292]
 [40.70678875]
 [80.81984762]
 [52.26141276]
 [ 6.6057882 ]]
Value of Square of Euclidean Norm of (Ax* - y) for regularised OLSLR  1.883107522182522
Time taken =  0.02233640500000078


In [14]:
from re import T
import numpy as np

np.random.seed(42)
A, y = np.random.randn(10, 10), np.random.randn(10, 1)
lambda_reg = 0.001
N, d = A.shape


def compute_fi(x, i):
    a_i = A[i]
    y_i = y[i]
    term2 = 0.5 * (a_i @ x - y_i) ** 2
    term1 = (lambda_reg / (2 * N)) * np.linalg.norm(x) **2
    return term1 + term2


def compute_grad_fi(x, i):
    a_i = A[i].reshape(1, -1)
    y_i = y[i]
    grad_term2 = (a_i @ x - y_i) * a_i.T
    grad_term1 = (lambda_reg / N) * x
    return grad_term1 + grad_term2


x = np.random.randn(d, 1)
for i in range(N):
  fi_value = compute_fi(x, i)
  grad_fi_value = compute_grad_fi(x, i)
  print(f"f_{i}(x): {fi_value}")
  print(f"Gradient of f_{i}(x):\n{grad_fi_value}")


f_0(x): [4.96422949]
Gradient of f_0(x):
[[ 1.56482405]
 [-0.43563717]
 [ 2.04070261]
 [ 4.79891365]
 [-0.73777506]
 [-0.73767394]
 [ 4.97568161]
 [ 2.41786854]
 [-1.47907628]
 [ 1.70953948]]
f_1(x): [15.93721128]
Gradient of f_1(x):
[[ 2.61609182]
 [ 2.62933408]
 [-1.36602285]
 [10.80191401]
 [ 9.73822442]
 [ 3.17449613]
 [ 5.71806382]
 [-1.77424027]
 [ 5.12648003]
 [ 7.9734159 ]]
f_2(x): [25.45965483]
Gradient of f_2(x):
[[-10.45859953]
 [  1.61106587]
 [ -0.48185396]
 [ 10.16680031]
 [  3.8845243 ]
 [ -0.79147848]
 [  8.21312391]
 [ -2.68097951]
 [  4.28608266]
 [  2.08150985]]
f_3(x): [0.0492521]
Gradient of f_3(x):
[[ 0.18739416]
 [-0.5774627 ]
 [ 0.00421387]
 [ 0.32999474]
 [-0.25645309]
 [ 0.38063629]
 [-0.06511809]
 [ 0.61082333]
 [ 0.41418512]
 [-0.06129761]]
f_4(x): [8.38090864]
Gradient of f_4(x):
[[-3.02344423]
 [-0.70157747]
 [ 0.47346542]
 [ 1.23295269]
 [ 6.05299007]
 [ 2.94704327]
 [ 1.88583305]
 [-4.32793256]
 [-1.40664512]
 [ 7.21789038]]
f_5(x): [2.07202813]
Gradient